
version: '3.8'

services:
  sistema-bicicleta-db:
    build:
      context: ./db
    ports:
      - "3306:3306"
    volumes:
  
      - ./db/datos_sql:/docker-entrypoint-initdb.d  # para cargar datos iniciales
  
  
  
  sistema-bicicleta-app:

    build:
        
      context: ./app

    depends_on: 
        - sistema-bicicleta-db 
   
    ports:
      - "3000:3000"

    


    
  
 
  


    




 

     








 