name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker-action@v2

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t your-dockerhub-username/sistema-bicicleta-app:${{ github.sha }} ./sistema-bicicleta-app
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push your-dockerhub-username/sistema-bicicleta-app:${{ github.sha }}

